data_dir: null
desc_file: null
goal: null
eval: null
log_dir: logs
workspace_dir: workspaces
preprocess_data: true
copy_data: true
exp_name: null
exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: false
generate_report: true
report:
  model: gpt-4-turbo
  temp: 1.0
agent:
  steps: 15
  k_fold_validation: 5
  expose_prediction: false
  data_preview: true
  code:
    model: gpt-4-turbo
    temp: 0.5
  feedback:
    model: gpt-4-turbo
    temp: 0.5
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 5
